### ISSUE TITLE
pylsl version is out of date?

### ISSUE THREAD

**Issue by BrainProducts** [timeflux/timeflux#7] opened 2019-04-11 16:26 UTC
In environment.yml, the pylsl version given is 1.10.5. When I tried to install on Windows 10, pip couldn't find this version. The latest version of pylsl is 1.13.1. I think this should be updated.

**Comment by BrainProducts** [comment] 2019-04-11 16:28
Hmmm... that didn't work either. Maybe I need to update pip in conda...

**Comment by BrainProducts** [comment] 2019-04-11 16:34
Ok, it is this problem: https://github.com/pypa/virtualenv/issues/1139

But, pylsl should still be updated :)

**Comment by mesca** [comment] 2019-04-11 17:39
PyLSL 1.12.2 was crashing on MacOS with double64 channels, so it was decided to (temporarily) freeze to 1.10.5. But now that 1.13.1 is out, I should give it another try, and investigate the problem further if it persists. Moving this on top of my todo list :)

**Comment by mesca** [comment] 2019-04-11 18:35
Ok, tests show that the problem is gone with the latest version. Updated in https://github.com/timeflux/timeflux/commit/fe902e0c70cebc8aa5e8aec187f501a8218d639d. Thanks for the reminder!

**Closed by mesca** 2019-04-11 18:35 UTC
